#ifndef TEXTURE_H
#define TEXTURE_H

#include <QtOpenGL/QtOpenGL>
#include <string>

class Texture
{
    GLuint tex; ///< The texture id generated by glGenTexture2D

public:
    Texture();
    void loadFromFile(const std::string &filename);
    void loadFromFile(const char *filename);
    void clearTexture();
    GLuint getTexture() const {return tex;}
};

#endif // TEXTURE_H
